### ISSUE TITLE
A user's thoughts on the usability of Director 4.0

### ISSUE THREAD

**Issue by al2me6** [tjcsl/director4#5]
First off, congratulations on release! It is to my knowledge that this has been in the works for quite a while.

Below are some thoughts that I had during my first experience with Director 4.0, as one of the maintainers of TJ Science Olympiad's website.

* I was entirely surprised to find that Director was undergoing maintenance when I attempted to push changes to the site on the 2020-08-22. Further, there was a period on 2020-08-23 during which any attempt to visit Director or a site hosted on Director resulted in a certificate error. While these issues did not significantly affect my team's operations, we would have appreciated an advanced notice so that we could prepare for the downtime as well as significant breakage (see below).
* Deprecated features should be indicated more clearly, perhaps by having a "what's new" section on the landing page. While I understand that implementing `git` integration may be difficult, it must be noted that its removal significantly impacts many workflows, including ours.
* There should be more documentation regarding how to use the new containerized architecture.
  * Transitioning to a Docker-based setup, in my view, requires a level of background knowledge that many Director users may not have and should not be expected to have. Namely, it requires familiarity with Docker as well as Linux package management.
  * That `git` was not installed on the default image was completely unexpected. Our site is hosted on Github and synced to Director using a `git` hook, a workflow that was previously recommended. While the removal of webhook support was noted, it was not indicated anywhere that `git` will need to be installed manually. I am of the opinion that at least some level of transition support should be provided. Might it be possible to include `git` (and other basic utilities such as `bash`) in the base Alpine image?
  * It might be prudent to include some warning as to the potential pitfalls of using a `musl`-based distro (Alpine): namely, that certain software will only run on a `glibc`-based distro. I realize that this is a rare occurrence, but providing a warning would prevent some head-scratching, should such a situation ever occur.

I hope that my thoughts are of some use to improving Director.

Alvin Meng

**Comment by sumanthratna** [comment]
> I was entirely surprised to find that Director was undergoing maintenance when I attempted to push changes to the site on the 2020-08-22

they had a banner and warnings in the Director 3 UI in the week leading up to the downtime, although maybe an email would've been nice.

> Deprecated features should be indicated more clearly, perhaps by having a "what's new" section on the landing page.

you may have already seen this but for others, there's a [What's New? page](https://director.tjhsst.edu/docs/whatsnew-director4/) in the docs

disclaimer: I'm not a sysadmin

**Comment by al2me6** [comment]
> they had a banner and warnings in the Director 3 UI in the week leading up to the downtime

Unfortunately, I did not see it because I did not have a need to visit Director during that time.

> you may have already seen this but for others, there's a What's New? page in the docs

I did find it! However, I think its visibility could be improved.

**Comment by ghost** [comment]
Hello Alvin,

In response to some of your questions/concerns:

- On June 30, we posted [an Ion announcement](https://ion.tjhsst.edu/announcements/4195) that announced that Director would have extended downtime over the summer, and that we would provide additional information with a banner on the Director dashboard. 
  This banner was added on August 9th and the migration was started on August 17th, so it was visible for about a week.

- There is a ["What's new"](https://director.tjhsst.edu/docs/whatsnew-director4/) page in the documentation. When I get a chance I'll work on adding something to the homepage.

- What specific background knowledge do you believe is required to use Director 4.0? Most of the Docker interaction is hidden from the user.
  Also, the default Python/Node.js/PHP images should work for simple sites. I don't believe that most users would need to install extra packages, or even worry about what Docker *is*.

- Currently, including `git` and/or `bash` in the default image is not really feasible because of the way that the Director 4.0 handles images. I have some ideas about restructuring things that would make this (and other image optimizations) easier, but unfortunately it's not going to happen anytime soon.

- I'll add a warning about musl vs. glibc to the Alpine image descriptions.

**Comment by theo-o** [comment]
Thank you for your interest in Director 4.0. In the interests of organization, non-accepted issues with more than a week of non-activity will be closed. 

As this issue has had more than 7 days without activity, it will be closed.
